### ISSUE TITLE
Factorial calculations doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#189]
```
Type in any number with an exclamation mark after it.
This should yield something like
12!=479001600
Instead you get no result found


Google handles this correctly (i.e. type in 12! into google and you get the 
answer) so I'm not sure what the problem is.

I am using this in the UK
```

Original issue reported on code.google.com by `e.i.a.lo...@gmail.com` on 11 Jun 2013 at 1:48

**Comment by DylanKlaassen** [comment]
Factorials (like 4! = 24) still do not work on my device. I also don't seem to get any error messages if I use an expression that Chromey can't handle on my device (I don't know if this is normal, or just the case form me. If it is normal, please consider including such an error message, because that would help with the usage of the program and understanding what does and doesn't work.)
Also, maybe I didn't look far enough, but I couldn't find a list (other than the source code, some of which I couldn't open on my device) with all the included expressions and their notations. I don't know if there is such a list, but it would be convenient to have a longer-than-basic list in the 'help' section of the program.
I hope this message can be of some help! Thanks for the awesome program :)
Btw, I live in the Netherlands and I use an acer chromebook, if that turns out to be relevant.
